### ISSUE TITLE
Mangadex multi-group

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#235]
Mangadex's latest addition to show multi-group. Please add it to the extension.

**Comment by CarlosEsco** [comment]
What is multigroup?

**Comment by Intervencion** [comment]
Joints.
Like, two groups collaborating with the same chapter

**Comment by CarlosEsco** [comment]
So multi scanlators shown in chapters view?

**Comment by Intervencion** [comment]
Think so, yeah

**Comment by bbtora** [comment]
> Joints.
Like, two groups collaborating in the same chapter

Yup, exactly that.
![chrome_2018-03-06_21-31-02](https://user-images.githubusercontent.com/23010526/37043062-c340e738-2185-11e8-967d-d38b1c149ee1.png)

**Comment by CarlosEsco** [comment]
Are you on 1.2.11? It shows for me

**Comment by CarlosEsco** [comment]
Just pull chapter list to refresh and it works

**Comment by CarlosEsco** [comment]
What manga in particular

**Comment by bbtora** [comment]
Kingdom(in the above pic), the newest chapter only shows the first group.

**Comment by CarlosEsco** [comment]
So a refresh should show it.  Kingdom shows for me but I didn't have it in my DB. Try refreshing again scanaltor change should show correctly. Also make sure you are on latest mangadex. You other option is remove from library then in advanced delete DB of non manga libraries. Then re add. But again a swipe to refresh should fix it

**Comment by CarlosEsco** [comment]
Here i what i see.

![image](https://user-images.githubusercontent.com/2092019/37052187-8c7ba52e-2146-11e8-8c5d-af01e5f7df34.png)

**Comment by bbtora** [comment]
nope, tried refreshing chapter list. also tried removing from library deleting DB but it still doesn't show.

**Comment by bbtora** [comment]
I see this too. but if you go to site page then you'll see what I'm talking about.

**Comment by CarlosEsco** [comment]
oh i see.  Let me see if json even shows that

**Comment by CarlosEsco** [comment]
It doesnt will talk to Holo

**Comment by CarlosEsco** [comment]
#237
