### ISSUE TITLE
Myreadingmanga covers still not loads

### ISSUE THREAD

**Issue by fatimagrace015** [inorichi/tachiyomi-extensions#432]
Even after the update. So I tried to uninstall and install it still wont load the covers. But mangas added in my library before this issue happened loads.

Tachiyomi ver: 0.7.4.
Myreadingmanga ver: 1.2.4

**Comment by fatimagrace015** [comment]
Cant provide a screenshot, dont know how to in phone

**Comment by CarlosEsco** [comment]
Clear your cache and cookies in settings

**Comment by fatimagrace015** [comment]
I tried. Still not loads

**Comment by CarlosEsco** [comment]
Yea just verified whatever fix was merged didn't work

**Comment by aurynluna** [comment]
Yeah still doesn't work.

**Comment by fatimagrace015** [comment]
My friend updated her mrm to 1.2.4 and she cant download at all, says 'not
used' though she reinstalled the source and cleared the cache and cookies

On 4 Aug 2018 14:10, "aurynluna" <notifications@github.com> wrote:

Yeah still doesn't work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/inorichi/tachiyomi-extensions/issues/432#issuecomment-410426795>,
or mute the thread

**Comment by fatimagrace015** [comment]
I just checked, me too cant download, but mangas I've added before this
issue occurred or before updating to 1.2.4 just downloads. If I read it
online its okay

**Comment by arkon** [comment]
Yeah, looks like they changed it on their end right after. :(
